"""
Django settings for tiny project.

Generated by 'django-admin startproject' using Django 4.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
# base_dir setting.py 所在文件路径.父文件



# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-1ygn)6%q=6nuk+@4p^3c7a=106pz7q4)^8ha(-e&9gdc=fpz)#'
# 秘钥 项目加密

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
# 打印项目运行信息

ALLOWED_HOSTS = ["*"]
# 允许的网络地址，可以设置为*允许任意访问


# Application definition

# 导入的app应用，类同于每一个页面功能
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # 注册users应用
    "users.apps.UsersConfig",
    # 注册transmit应用
    "transmit.apps.TransmitConfig",
    # 注册mysql应用
    "mysql.apps.MysqlConfig"
]

# django内置的配置信息
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 请求体默认加密
    # 'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
# mysql是关系型数据库，同一条数据字段有关联
# redis是非关系型数据库，存储方式为：key和value
# 定义session存储路径 存在redis存储服务器中

#  源url地址
ROOT_URLCONF = 'tiny.urls'

# 模板：后期显示html代码
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# web连接接口
WSGI_APPLICATION = 'tiny.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases
# 轻量级数据库：app应用
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

# 权限密码认证
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

# 语言 默认en-us
# 中文默认语言  zh-hans
LANGUAGE_CODE = 'en-us'
# 时区 时区 Asia/Shanghai
TIME_ZONE = 'UTC'
# 使用者用户信息
USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

# 静态资源路径 图片，音频、css,js
STATIC_URL = 'static/'

# 静态文件配置
STATICFILES_DIRS = [
    # join 拼接
    os.path.join(BASE_DIR, "static_files")
]

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
# 配置默认的session存储redis
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379/1", # 安装redis的主机的 IP 和 端口 使用redis1号数据库
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient"
            # "CONNECTION_POOL_KWARGS": {
            #     "max_connections": 1000,
            #     "encoding": 'utf-8'
            # },
            # "PASSWORD": "foobared" # redis密码
        }
    }
}
SESSION_ENGINE = "django.contrib.sessions.backends.cache"
SESSION_CACHE_ALIAS = "default"

# 配置mysql
DATABASES = {

    'default': {
        'ENGINE': 'django.db.backends.mysql', # 数据库产品
        'HOST': '127.0.0.1', # 数据库主机
        'PORT': 3306, # 数据库端口
        'USER': 'root', # 数据库用户名
        'PASSWORD': '123456', # 数据库用户密码
        'NAME': 'tiny' # 数据库名字

    }

}
